### PR TITLE
Restructure amazon vpc module into submodules

### PR DESCRIPTION
**Pull request by andersla**
Restructure amazon vpc module into submodules to allow for user defined vpc and subnet and lookup function for kubenow image name to image_id

### CODE REVIEW

**Comment by andersla** [comment]
I see that I will need to do a pull request for changing amazon image_id to kubenow_image name in travis for this to work

**Comment by mcapuccini** [comment]
@andersla I'll show to you tomorrow how to fix this. In the meanwhile please send a PR to update the docs.

**Comment by mcapuccini** [comment]
@andersla please reference the docs PR

**Comment by mcapuccini** [comment]
@andersla please fix the titles of your PR, it gets hard otherwise to read

**Comment by andersla** [comment]
Updated docs: kubenow/docs#9

**Comment by mcapuccini** [comment]
Nice job!

**Pull request merged**
