### PR TITLE
Fixes kn ssh as recognized command and updates kn-ssh

### PR DESCRIPTION
**Pull request by andersla**
## Change content and motivation
Fixes kn ssh as recognized command and updates kn-ssh

## GitHub cross-links 

**Fixes:** 
#290 
**Docs**:

### CODE REVIEW

**Comment by mcapuccini** [comment]
@andersla is there any way we can add `kn ssh` to travis so it gets tested during the CI process?

**Comment by andersla** [comment]
Good suggestion, I'll add it and try to add test for azure and gcloud also

**Comment by andersla** [comment]
Closed it by accident, adding travis test

**Comment by andersla** [comment]
OK done with more testing:-)

**Comment by mcapuccini** [comment]
@andersla please fix conflicts and we are ready to go!

**Pull request merged**
