### PR TITLE
KubeNow CLI

### PR DESCRIPTION
**Pull request by mcapuccini**
## Change content and motivation
This PR add a `kn` command that wraps around a Docker container to make the installation of ansible and terraform easier for the user (and to solve tedious versioning problems with ansible and terraform).

## GitHub cross-links 

**Fixes:** 

**Docs**:

### CODE REVIEW

**Comment by mcapuccini** [comment]
@andersla is not bulletproof yet, but you might want to try it. I will add tests soon... there might be a problem with file permission when running it on linux (on Mac seems to work good).

To test:

```
ln -s bin/kn /usr/local/bin/
kn init my-deployment
cd my-deployment 
# fill a template (e.g. openstack) ...
kn terraform get openstack
kn terraform apply openstack
kn ansible-playbook playbooks/install-core.yml
ssh-add ssh-key
ssh ubuntu@...
# enjoy!
```

**Comment by mcapuccini** [comment]
pinging also @carmat88 @jonalv @StaffanArvidsson for more tests/opinions on the CLI.

**Comment by andersla** [comment]
Very cool Marco! I am really looking forward to read in and test it! Now off to meet a friend at the pub! Have a nice rest of the weekend!

**Comment by mcapuccini** [comment]
You also need to build the Dockerfile to test...

Il 26 mag 2017 6:26 PM, "Anders Larsson" <notifications@github.com> ha
scritto:

**Comment by mcapuccini** [comment]
closing in favour of #201

**Pull request closed without merging**
