### PR TITLE
Feature/openstack flavor

### PR DESCRIPTION
**Pull request by andersla**
@mcapuccini This is for resolving sneumans flavor_id. Excited to see if it tests OK!

### CODE REVIEW

**Comment by mcapuccini** [comment]
@andersla you need to merge the master into this branch, or the test is not going to run

**Comment by mcapuccini** [comment]
please add some documentation for this new feature, we should me some effort to update the docs straight away from now. I am updating it, and it is difficult to remember everithing now.

**Comment by andersla** [comment]
@mcapuccini It worked! This is sooo coool!!

**Comment by mcapuccini** [comment]
@andersla please merge the master to start the CI process

**Pull request merged**
