### PR TITLE
Changed object-store-sc settings

### PR DESCRIPTION
**Pull request by jonandernovella**
Tweaks to improve GlusterFS performance on VMs. Read more: https://access.redhat.com/documentation/en-us/red_hat_gluster_storage/3.2/html/configuring_red_hat_virtualization_with_red_hat_gluster_storage/chap-hosting_virtual_machine_images_on_red_hat_storage_volumes

### CODE REVIEW

**Comment by mcapuccini** [comment]
@jonandernovella I'd rather have this additional storage class as a helm package, so then you can tweak as much as you want with no need to send additional PRs. What do you think?

**Comment by mcapuccini** [comment]
Can we make a helm chart called s3-interface? Having this storage class, and triggering minio install as well?

**Comment by jonandernovella** [comment]
@mcapuccini We can, yes. Though I really prefer much more this solution since we use official packages and SC, with best practcices atm.

**Comment by jonandernovella** [comment]
@mcapuccini Anyway, this is just a PR for the `phnml` branch- We can discuss about `master` later on :)

**Comment by mcapuccini** [comment]
But then you need to parametrize this options, we can't change them again and again. In my opinion is way simpler via Helm. But it is up to you.

**Comment by mcapuccini** [comment]
Ok! Up to @andersla then 🙂

**Comment by andersla** [comment]
I would suggest parameterize {{volumeoptions}} as  {{volumetype}}.
Maybe put the default value in the heketi role defaults/main.yml ?

**Comment by andersla** [comment]
I think you can create a multiline variable (since it is a very long string) described here: http://docs.ansible.com/ansible/latest/YAMLSyntax.html

**Comment by andersla** [comment]
Looks good! I'll merge it into phenomenal/stable - I think it should go into master as well

**Pull request merged**
