### PR TITLE
Using new stable image v040

### PR DESCRIPTION
**Pull request by carmat88**
Hello @mcapuccini . As per discussion, here are the necessary changes in order to use the latest stable Kubenow image v040. Any comments please let me know. Cheers.

### CODE REVIEW

**Comment by mcapuccini** [comment]
Thanks! 🙂

**Comment by mcapuccini** [comment]
@carmat88 there is some problem with the OpenStack image, I tried to restart it many times and instances error when they try to start. Can you and @andersla give it a look? I also restarted the master and it passed straight away. Maybe try to start the image manually, and see if it works... otherwise you can try to remove the image, and to restart the CI for this PR so it gets imported again. Another possible test is to try to download the image from the bucket manually and try to start it in another OpenStack or region withing SSC.

**Comment by carmat88** [comment]
@mcapuccini Sure thing. I will first run your suggested checks, otherwise will ping Anders.

**Comment by mcapuccini** [comment]
@carmat88 it seems like there is some problem with OpenStack, could you check it?

**Comment by carmat88** [comment]
@mcapuccini @andersla Despite having resource available on SNIC, only for this particular building is keep failing. I can confirm that v040 is not corrupted in any places: all v040 in cityCloud and amazon buckets can be downloaded and/or used to successfully launch single instances in cityCloud, AWS and even SNIC itself (HPC2N, manually upload via glance).

After being able to launch single VMs with the manually uploaded v040 taken from Amazon, I then re-run this CI for Openstack. Yet Terraform fails by reporting the following:

```
Error applying plan:

1 error(s) occurred:

* module.master.openstack_compute_instance_v2.instance: 1 error(s) occurred:

* openstack_compute_instance_v2.instance: Error waiting for instance (49a4a7ee-eae4-403f-92a3-17c90f86398b) to become ready: unexpected state 'ERROR', wanted target 'ACTIVE'. last error: %!s(<nil>)
``` 

Tbh, I am unclear why it is failing. So I reckon it might be something about passing the image name to the terraform file as Marco suggested. Cheers.

**Comment by carmat88** [comment]
Hello @mcapuccini ! Eventually together with @andersla we managed to pinpoint what was the tiny but so determinant detail that had made failing over and over. That is, an inappropriate initial `OS_FLAVOR` set in Travis which packer was using to create the openstack image (`8C-8GB-50GB`). In fact, originally I selected one with 50GB of disk, too much of what is needed for our KubeNow image. Thus Terraform was failing to spawn machines in HPC2N because the `ssc.medium` flavor did not have a matching block mapping device. Now I am using the following flavor: `6C-6GB-20GB` which should not slow down too much the image creation process and at the same time it uses an appropriate disk size.

Any comments, please let me know. Cheers!

**Comment by mcapuccini** [comment]
@carmat88 I see! I think that 6C-6GB-20GB is still quite large, there may be users that want to run with smaller nodes. Could you please rerun the release with 2C-4GB-20GB? This would be similar to the flavors that we use for the other providers.

**Comment by andersla** [comment]
The number of cores and internal memory at packer build time shouldn't affect the image. Only the root disk size. You should be OK with 6C-6GB-20GB

**Pull request merged**
