### PR TITLE
Add hostname to hosts file as part of bootstrap script

### PR DESCRIPTION
**Pull request by andersla**
## Change content and motivation
Adds hostname to /etc/hosts - needed on some cloud providers for resolving hostname 

## GitHub cross-links 

**Fixes:** 

**Docs**:

### CODE REVIEW

**Comment by mcapuccini** [comment]
@andersla HOSTNAME is unset on OpenStack. Please use `echo "127.0.0.1 $(hostname)" >> /etc/hosts`

**Comment by mcapuccini** [comment]
The CI timed out, please remove the resources manually.

**Comment by andersla** [comment]
No I tested locally on Citycloud - Hostname is inserted OK. Some other problems with ssh-connection and citycloud from travis I guess.

**Comment by mcapuccini** [comment]
@andersla thanks for sorting this out!

**Pull request merged**
