### PR TITLE
Remove object store SC

### PR DESCRIPTION
**Pull request by mcapuccini**
## Change content and motivation
Taking out object storage SC until we know better how to manage it.

### CODE REVIEW

**Comment by mcapuccini** [comment]
@jonandernovella I need to make 0.3.1 and I didn't manage properly the 0.3 branch, so I need to remove this temporarly. Is it ok? It should be safe in phenomenal right?

**Comment by jonandernovella** [comment]
@mcapuccini The settings in the `phenomenal` branch are the appropriate ones for the `object-store-sc`. We better merge that instead. What do you think?

**Comment by mcapuccini** [comment]
Sure. I need to make a stable first though. I messed up the stable branch, so I need to merge this in the master first. Could you send me a PR after this?

**Comment by jonandernovella** [comment]
LGTM!

**Pull request merged**
