### PR TITLE
Using new stable image 051

### PR DESCRIPTION
**Pull request by carmat88**
## Change content and motivation
Using new stable image 051

### CODE REVIEW

**Comment by carmat88** [comment]
@andersla may I ask your advice here? It seems that kn-apply is failing for OS and AWS although the image is present in both tenancies. Cheers.

**Comment by andersla** [comment]
Maybe something with newer version of Ubuntu base image (in case of aws)?

**Comment by andersla** [comment]
On Openstack: No more IP addresses available on network 52b76a82-5f02-4a3e-9836-57536ef1cb63

**Comment by andersla** [comment]
Two independent errors:-) I have alreade filed issue to hpc2n about lack of floating-ip:s

**Comment by carmat88** [comment]
Ok, eventually OS was successful. For AWS, I've rebuilt v051 and now it's working correctly as well. I'm [revising the security updates script for AWS](https://github.com/kubenow/image/pull/48) (hence the cron script has been temporarily disabled). However, the latest stable v051 can be used if need be. Cheers.

**Pull request merged**
