### PR TITLE
Fix Helm privilege escalation

### PR DESCRIPTION
**Pull request by carmat88**
Removing line 3 (`become: yes`) in the [`main.yml`](https://github.com/kubenow/KubeNow/blob/master/playbooks/roles/start-helm/tasks/main.yml) file for the Helm's playbook so to remove privilege escalation for Helm.

Fix: https://github.com/kubenow/KubeNow/issues/103

### CODE REVIEW

**Comment by mcapuccini** [comment]
@carmat88 looks good. Would you mind to remove the [skip ci]? So it will get tested.

**Comment by carmat88** [comment]
Sorry, I messed the revert action and no files were actually pushed within the reverted commit. Not sure why Travis failed though.

**Comment by mcapuccini** [comment]
@carmat88 the CI failed because of breaking kubeadm update. We will merge this after you are done with the image refactory, that should solve the issue :)

**Comment by carmat88** [comment]
Ok sure, it makes sense. Thanks for the info. Will keep working the image creation refactory then.

**Comment by mcapuccini** [comment]
@carmat88 CI is not fixed. Tests are running now.

**Comment by carmat88** [comment]
@mcapuccini Ok, thanks for the heads-up.

**Pull request merged**
