### PR TITLE
User configurable port opening

### PR DESCRIPTION
**Pull request by andersla**
## Change content and motivation
Allow user to configure port openings (as a list of ports) for inbound traffic on all cloud providers

Docs: kubenow/docs#39

### CODE REVIEW

**Comment by carmat88** [comment]
Hey @andersla ! Is this still a _[work in progress]_, or should it be done? Also, given the title, I wanted to ask whether we are offering **"only"** the explicit configuration of some ports to be open by default or **also** the option for users to add other ports. If the latter was true, how would one do it? Many thanks for further expanding the above comments! Cheers.

**Comment by andersla** [comment]
Docs: kubenow/docs#39

**Comment by andersla** [comment]
Docs: kubenow/docs#39

**Comment by andersla** [comment]
OK, ready now

**Comment by andersla** [comment]
OK ready now

**Comment by andersla** [comment]
I think this repetition was because of githubs issues this morning

**Pull request merged**
