### PR TITLE
WIP:add disc format

### PR DESCRIPTION
**Pull request by stephenmoloney**
## Change content and motivation

- `qcow2` disc_format is potentially incompatible with some cloud providers

```shell
Unable to set 'disk_format' to 'qcow2'. Reason: u'qcow2' is not one of [None, u'raw']

Failed validating u'enum' in schema[u'properties'][u'disk_format']:
    {u'description': u'Format of the disk',
     u'enum': [None, u'raw'],
     u'type': [u'null', u'string']}

On instance[u'disk_format']:
    u'qcow2'
```

What does this MR do?

- Adds `disc_format` as an option

What is there to be completed

- [ ] testing 
- [ ] establishing a sensible default.. perhaps it should be left as `qcow2` default format.
- [ ] the aws server does not have formats other than `qcow2`

### CODE REVIEW

**Comment by stephenmoloney** [comment]
An alternative approach which I sort of like due to the long wait time to dowload the kubenow image is to add the kubenow image to the docker image... At least then it doesn't have to be downloaded on every time `kn apply` runs the docker container. I started some work on that alternative approach [here](https://github.com/stephenmoloney/KubeNow/commit/b8bb5d0269a2a52edde1e494f9590a2642c0fa0e)

**Comment by mcapuccini** [comment]
@stephenmoloney thanks for opening this PR. I think that the image gets downloaded only the first time, and then there should be a check that skips the download if the image is already present in the tenancy. So, I'd rather keep this current approach, as we should try to keep the Docker image as light as possible. Please let me know when you have something working, so I can review and enable the CI.

@carmat88, @andersla any ideas on this?

**Comment by mcapuccini** [comment]
If the image gets downloaded every time it might be due to recent breaking developments with security updates for images. @carmat88 do I need to merge anything to make this not happening?

**Comment by carmat88** [comment]
@mcapuccini No, the currently queued PR in the image repo is not meant to fix any breakings. Also we do not have any cron-job running for the time being. Though I've noticed various PRs for Kubenow, so I wonder if there was anything there meant to be a fix?

**Comment by mcapuccini** [comment]
@carmat88 Yep, exactly. @andersla merged a fix recently that solves the issue of image re-download. I will make a 0.3.2 stable that will sort things out.

**Comment by stephenmoloney** [comment]
I can confirm that the image doesn't keep downloading provided it has been successfully uploaded... sorry if that is a bit misleading.... I think not putting the image inside the docker image is reasonable to keep the docker image small..

But if the server does not accept a `qcow2` disc_format, I'm not sure best approach. Perhaps, making a `raw` image and a `qcow2` image available is an option?

**Comment by stephenmoloney** [comment]
closing in favour of [this PR instead](https://github.com/kubenow/KubeNow/pull/374)

**Pull request closed without merging**
